### ISSUE TITLE
Invalid leverage/margin calculation

### ISSUE THREAD

**Issue by imphocused** [EarnForex/PositionSizer#44]
![Screen Shot 2022-06-25 at 10 11 04 PM](https://user-images.githubusercontent.com/501310/175797792-9362a478-0134-4aeb-9cf1-98dff3c3d42c.png)

Is it possible to adjust how the leverage is calculated? On this broker (Dominion Markets, MT5) the calculations for crypto are off. 

![Screen Shot 2022-06-25 at 10 18 24 PM](https://user-images.githubusercontent.com/501310/175798025-5a5b6f58-84d6-4e5a-a08e-9cd2dbd72440.png)

**Comment by EarnForex** [comment]
Hello imphocused!

The problem here is that the symbol's calculation mode is reported as SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE, while in reality it looks more like SYMBOL_CALC_MODE_CFD is used.

In SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE, margin is calculated as Lots * Contract_Size * Margin_Rate. The price of the symbol isn't taken into account or is taken care of by the Margin_Rate (reported by the broker's server).

In SYMBOL_CALC_MODE_CFD, margin is calculated as Lots * ContractSize * MarketPrice * Margin_Rate. This would yield a correct result here.

So, the broker should either fix the reported SYMBOL_TRADE_CALC_MODE or Margin_Rate on its server.

**Comment by EarnForex** [comment]
Hello!

Here is what the MQL5 help file says about `SYMBOL_CALC_MODE_FOREX_NO_LEVERAGE`:
![Screenshot 2022-06-30 154035](https://user-images.githubusercontent.com/48102957/176679385-7bed03fa-824f-43c7-8d7a-7116f4e12f63.png)

And indeed, if you open a trade of 1 lot, then you'll see that it takes 1/10 of margin, which is consistent with 0.1 Margin Rate application.

So, in reality, even though it says "Forex No Leverage", it would be 1:10 real leverage.

**Comment by EarnForex** [comment]
Doesn't look like a Position Sizer issue at this time.
