### ISSUE TITLE
Add boolean to be able to send SL/TP with Market orders

### ISSUE THREAD

**Issue by ericogit** [EarnForex/PositionSizer#51]
Would be great if you could add an boolean so that the EA sends a SL/TP with the Market orders.
Because some prop firms do not allow sending market orders without a SL attached to the order.

**Comment by EarnForex** [comment]
Will be fixed the next version.

**Comment by lueny-toons** [comment]
> Would be great if you could add an boolean so that the EA sends a SL/TP with the Market orders.
> Because some prop firms do not allow sending market orders without a SL attached to the order.

Yup... I concur. Need this feature as those doing Prop Trading with certain firms require at the very least SL in place upon trade executed. The time allowance given is 1 minute or thereabouts before violation is recorded. With 3 violations the account is terminated. So, this is a big worry for us prop traders

But since the owner/creator has mentioned will be fixed in the next version... Great stuff. Thanks

p/s. love your work and outstanding features with this Position Sizer EA. 2-thumbs up mate...

**Comment by EarnForex** [comment]
Should be addressed in 3.03.
