### ISSUE TITLE
Hotkey modifier for increase/decrease arrows

### ISSUE THREAD

**Issue by BarbzYHOOL** [EarnForex/PositionSizer#88]
hello,

when i want to add a second order to add up to the first one, as a pending order, the stop loss is set on the previous stop loss which is logic
But then I cannot drag the line down else it will move the previous trade SL

So, the only way is to change the number in the panel.
On Nasdaq, if I click on the little arrow to change the SL, it takes forever because its value is like 18000 and it only moves by 0,01
Maybe add a hotkey modifier like Alt or Shift or Ctrl when we left click on the little arrows so it moves by x100 or x1000

I hope I made it clear

**Comment by EarnForex** [comment]
Hello!

That's an interesting idea! However, you can easily fix the underlying issue (dragging the SL line without dragging the previous trade's SL) by going to the _Tools->Options->Charts_ and either disabling _Show trade levels_ or ticking _Use 'Alt' key to drag trade levels_. I recommend doing the latter even when not using Position Sizer because it helps you avoid dragging the lines accidentally.
